config/routes.rb
Rails.application.routes.draw do

   root 'courses#index'
   resources :users
   resources :courses

   get '/sign-up' => 'registrations#new', as: :signup
   post '/sign-up' => 'registrations#create'
   get '/sign-in' => 'sessions#new', as: :signin
   post '/sign-in' => 'sessions#create'
   get '/sign-out' => 'sessions#destroy', as: :signout

end

app/models/course.rb
class Course < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  validates :user_name, presence: true, uniqueness: true

 has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  User.find_by(id: session[:user_id])
  end

  helper_method :current_user
  
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to courses_path, notice: 'Course was successfully created'
    else
      flash.now[:alert] = @course.errors.full_messages
      render :new
    end
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])

    if @course.update_attributes(course_params)
      redirect_to courses_path, notice: 'Course was successfully updated'
    else
      flash.now[:alert] = @course.errors.full_messages
      render :edit
    end
  end

  def destroy
    @course = Course.find(params[:id])
    if @course.destroy
      redirect_to courses_path, notice: 'Course was successfully deleted'
    end
  end

  def course_params
    params.require(:course).permit(:title, :day_night)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  private
    def user_params
      params.require(:user).permit(:user_name, :password, :about)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_user_name(params[:user_name])
    if user &&
      user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      @sign_in_error = "Username / password combination is invalid"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path, notice: 'User was successfully created'
    else
      flash.now[:alert] = @user.errors.full_messages
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to users_path, notice: 'User was successfully updated'
    else
      flash.now[:alert] = @user.errors.full_messages
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:user_name, :password, :about)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def human_boolean(boolean)
    boolean ? 'Day' : 'Night'
  end
end

app/views/courses/_form.html.erb
<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

<%= form_for @course do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<br/>
<%= f.label :day_night, "Day" %>
<%= f.radio_button :day_night, true %>
<%= f.label :day_night, "Night" %>
<%= f.radio_button :day_night, false %>
<br />
<%= f.submit %>
<% end %>

app/views/courses/edit.html.erb
<h1> Edit Course </h1>

<%= render 'form' %>

app/views/courses/index.html.erb
<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

<h1>All Courses</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Day or Night</th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
    <tr>
      <td><%= link_to course.title, course %></td>
      <td><%= human_boolean(course.day_night) %></td>
      <td><%= link_to 'Delete Course', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<br/>
<%= link_to "Create a New Course", new_course_path %>
<br/>
<%= link_to "See all Users", users_path %>

app/views/courses/new.html.erb
<h1>Create a New Course</h1>
<%= render 'form' %>

app/views/courses/show.html.erb
<h1>Course Details</h1>
<p>Title: <%= @course.title %></p>
<p>Day or night: <%= human_boolean(@course.day_night) %></p>

<%= link_to "Edit Course", edit_course_path(@course) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KerryRobertsWeek7</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div>
    <% if current_user %>
      <%= link_to "Sign Out", signout_path %>
    <% else %>
      <%= link_to "Sign Up", signup_path %>
      |
      <%= link_to "Sign In", signin_path %>
    <% end %>
  </div>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

<%= form_for @user do |f| %>
<%= f.label :user_name %>
<%= f.text_field :user_name %>
<br />
<%= f.label :about %>
<%= f.text_field :about%>
<br />
<% if @user.id == nil %>
  <%= f.label :password %>
  <%= f.password_field :password %>
<% end %>
<br />
<%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1> Edit User </h1>

<%= render 'form' %>

app/views/users/index.html.erb
<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

<h1>All Users</h1>

<table>
  <thead>
    <tr>
      <th>User Name</th>
      <th>About</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.user_name, user %></td>
        <td><%= user.about %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br/>
<%= link_to "Create a New User", new_user_path %>
<br/>
<%= link_to "See all the Courses", courses_path %>

app/views/users/new.html.erb
<h1>Create a User</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1> <%= @user.user_name %> </h1>
<p> About: <%=@user.about %> </p>

<%= link_to "Edit User", edit_user_path(@user) %>